import Link from 'next/link'

import { Metadata } from 'next'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { RocketIcon } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Home | Linkvertex',
  description: 'Generated by abdul basit interesting blogs,projects,smile and others... 2023',
  icons: {
    icon: ['/favicon.ico?v=4'],
    apple: ['/public/favicon.ico?v'],
    shortcut: ['/public/favicon.ico?v=4'],
  },
  alternates: {
    canonical: 'http://linkvertex.a-bd.me/',
  },
}

export default function Home() {
  return (
    <>
      <main className={'container'}>
        <div className={'mt-[14.5rem] max-md:mt-[14rem] flex items-center flex-col justify-center gap-[3.5rem] max-md:gap-[2rem]'}>
          <h1 className={'main-text-animation w-[410px] text-[3.80rem] text-center leading-[110%] font-[800] max-md:text-[48px] max-md:w-[508px] max-sm:w-[450px] max-[530px]:w-full'}>One Place for All Your Links</h1>
          <p className={'w-[410px] font-[600] text-white leading-[1.5rem] text-center max-sm:w-[85%]'}>One link to rule them all. Easily place your links in a beautiful single page.</p>
          <Link href={'/sign-up'} className={'px-[24px] py-[12px] rounded-[20px] font-[600] text-[18px] bg-[#FCD28D] hover:bg-[#EBB064] transition-all'}>
            Get Started
          </Link>
        </div>
      </main>
    </>
  )
}
